### ISSUE TITLE
ImportError: No module named numpy.distutils.core

### ISSUE THREAD

**Issue by liuyou6046** [mblondel/soft-dtw#11]
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from numpy.distutils.core import setup
ImportError: No module named numpy.distutils.core

When I follow your step, but why I have the Error?

**Comment by v-nhandt21** [comment]
> Traceback (most recent call last):
> File "setup.py", line 5, in
> from numpy.distutils.core import setup
> ImportError: No module named numpy.distutils.core
> 
> When I follow your step, but why I have the Error?

I fail in same issue, do you remember how to solve this?
