### ISSUE TITLE
How to use it as the loss function for deep learning framework(tensorflow, keras,...)

### ISSUE THREAD

**Issue by sculyi** [mblondel/soft-dtw#8]
I define te function as following:
def test_loss(y_pred, y_true):
    return tsm_sdtw(y_pred, y_true)

and compile it with keras model ==>  model.compile(optimizer='Adam', loss=test_loss)
However, the following error are shown:
  File "D:\python35\lib\site-packages\keras\engine\training.py", line 910, in compile
    sample_weight, mask)
  File "D:\python35\lib\site-packages\keras\engine\training.py", line 436, in weighted
    score_array = fn(y_true, y_pred)
  File "D:/Q/cdads/py_code/turn_upsample.py", line 17, in test_loss
    return tsm_sdtw(y_pred, y_true)
  File "D:\python35\lib\site-packages\tslearn\metrics.py", line 597, in soft_dtw
    return SoftDTW(SquaredEuclidean(ts1[:ts_size(ts1)], ts2[:ts_size(ts2)]), gamma=gamma).compute()
  File "D:\python35\lib\site-packages\tslearn\utils.py", line 320, in ts_size
    ts_ = to_time_series(ts)
  File "D:\python35\lib\site-packages\tslearn\utils.py", line 84, in to_time_series
    ts_out = ts_out.astype(numpy.float)
ValueError: setting an array element with a sequence.
@mblondel 
Would you please give some toy examples for this.

**Comment by mblondel** [comment]
Keras and tensorflow are not supported.

**Comment by Luucky** [comment]
Any chance you could elaborate, why these aren't supported? I am currently trying to implement a DTW distance cost function in TensorFlow but cannot find any information about it.

**Comment by mblondel** [comment]
An efficient implementation of soft-DTW requires custom gradients. Moreover, it needs to store temporary computations from the forward pass and reuse them during the backward pass. Here's how it is implemented in Chainer:

https://github.com/mblondel/soft-dtw/blob/master/sdtw/chainer_func.py

Back when I wrote soft-DTW, it was not possible to do the same in Tensorflow.

**Comment by THHHomas** [comment]
@mblondel Could you please provide the keras version of sdtw? I guess lots of people need the version. Chainer is a very good deep learning framework, but at least currently, it is not the main stream. thanks a lot.

**Comment by shaform** [comment]
I think it's possible to implement it in Tensorflow, it's just that maybe the C++ based ops are required. See https://www.tensorflow.org/guide/extend/op.

**Comment by Abhay242** [comment]
can DTW loss be implemented in Pytorch, as it is also a Dynamic Graph Computation framework like Chainer? @mblondel

**Comment by KIC** [comment]
@Abhay242 there is a pytorch implementation: https://github.com/lyprince/sdtw_pytorch/blob/master/sdtw.py

@mblondel at least with tensorflow 1.15 it seems to be possible https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/custom_gradient

a tensorflow version would really be nice!
